### ISSUE TITLE
Set Dell OneTimeBoot VirtualCD does not work with recent iDRAC9 versions

### ISSUE THREAD

**Issue by akiselev1** [sonofspike/cluster_mgnt_roles#60]
I found that node discovery fails for a Dell baremetal server with iDRAC9 version 4.40.40. Task `Set Dell OneTimeBoot VirtualCD` in cluster_mgnt_roles/boot_iso/tasks/dell_redfish.yml succeeds, but Dell server with iDRAC 4.40.40  still boots from HDD. Node discovery fails because of that.

I am not sure why this task uses a direct API call, which works only up to a certain iDrac version. Probably there is some historical reason for that. I suggest using this block instead:
```
- block:
    - name: Set Dell OneTimeBoot VirtualCD (VCD-DVD)
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: VCD-DVD
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}"
  rescue:
    - name: Set Dell OneTimeBoot VirtualCD (Cd)
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: Cd
        baseuri: "{{ hostvars[inventory_hostname]['bmc_address'] }}"
        username: "{{ hostvars[inventory_hostname]['bmc_user'] }}"
        password: "{{ hostvars[inventory_hostname]['bmc_password'] }}" 

```
It works with the latest community.general version. Just make sure you got the latest: `ansible-galaxy collection install community.general --force`

Workaround: roll back iDRAC version to 4.22. This original task API call works with that.
